version: '3.8'
services:
  hyperion:
    image: postgres:13.3-alpine
    container_name: hyperion
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: ${PGDATA}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - hyperion_data:/var/lib/postgresql/data

volumes:
  hyperion_data:
